export const brands = [
  { brandName: 'html5', mdiIcon: 'mdi-language-html5', humanReadable: 'HTML5', url: 'https://html.spec.whatwg.org/', brandPrimary: '#E34F26'  },
  { brandName: 'css3',  mdiIcon: 'mdi-language-css3', humanReadable: 'CSS3', url: 'https://www.w3.org/Style/CSS/', brandPrimary: '#1572B6' },
  { brandName: 'javascript',  mdiIcon: 'mdi-language-javascript', humanReadable: 'JavaScript', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', brandPrimary: '#F7DF1E', color: '#323330' },
  { brandName: 'typescript',  mdiIcon: 'mdi-language-typescript', humanReadable: 'TypeScript', url: 'https://www.typescriptlang.org/', brandPrimary: '#3178C6' },
  { brandName: 'react', mdiIcon: 'mdi-react', humanReadable: 'React', url: 'https://reactjs.org/', brandPrimary: '#61DAFB', color: '#20232A'},
  { brandName: 'vuejs', mdiIcon: 'mdi-vuejs', humanReadable: 'Vue.js', url: 'https://vuejs.org/', brandPrimary: '#42B883', color: '#35495E' },
  { brandName: 'angular', mdiIcon: 'mdi-angular', humanReadable: 'Angular', url: 'https://angular.io/', brandPrimary: '#DD0031' },
  { brandName: 'svelte', mdiIcon: 'mdi-svelte', humanReadable: 'Svelte', url: 'https://svelte.dev/', brandPrimary: '#FF3E00'},
  { brandName: 'nodejs', mdiIcon: 'mdi-nodejs', humanReadable: 'Node.js', url: 'https://nodejs.org/', brandPrimary: '#339933'},
  { brandName: 'expressjs', mdiIcon: 'mdi-web', humanReadable: 'Express.js', url: 'https://expressjs.com/', brandPrimary: '#000000' },
  { brandName: 'php', mdiIcon: 'mdi-language-php', humanReadable: 'PHP', url: 'https://www.php.net/', brandPrimary: '#777BB4' },
  { brandName: 'python', mdiIcon: 'mdi-language-python', humanReadable: 'Python', url: 'https://www.python.org/', brandPrimary: '#3776AB', color: '#FFD43B' },
  { brandName: 'django', mdiIcon: 'mdi-web', humanReadable: 'Django', url: 'https://www.djangoproject.com/', brandPrimary: '#092E20'},
  { brandName: 'rubyonrails', mdiIcon: 'mdi-language-ruby-on-rails', humanReadable: 'Ruby on Rails', url: 'https://rubyonrails.org/', brandPrimary: '#CC0000' },
  { brandName: 'aspnet', mdiIcon: 'mdi-microsoft-azure', humanReadable: 'ASP.NET', url: 'https://dotnet.microsoft.com/apps/aspnet', brandPrimary: '#512BD4' },
  { brandName: 'bootstrap', mdiIcon: 'mdi-bootstrap', humanReadable: 'Bootstrap', url: 'https://getbootstrap.com/', brandPrimary: '#7952B3' },
  { brandName: 'tailwindcss', mdiIcon: 'mdi-tailwind', humanReadable: 'Tailwind CSS', url: 'https://tailwindcss.com/' },
  { brandName: 'jquery', mdiIcon: 'mdi-jquery', humanReadable: 'jQuery', url: 'https://jquery.com/' },
  { brandName: 'webpack', mdiIcon: 'mdi-webpack', humanReadable: 'Webpack', url: 'https://webpack.js.org/' },
  { brandName: 'vite', mdiIcon: 'mdi-lightning-bolt', humanReadable: 'Vite', url: 'https://vitejs.dev/' },
  { brandName: 'gatsby', mdiIcon: 'mdi-react', humanReadable: 'Gatsby', url: 'https://www.gatsbyjs.com/' },
  { brandName: 'nextjs', mdiIcon: 'mdi-react', humanReadable: 'Next.js', url: 'https://nextjs.org/' },
  { brandName: 'nuxtjs', mdiIcon: 'mdi-vuejs', humanReadable: 'Nuxt.js', url: 'https://nuxtjs.org/' },
  { brandName: 'mongodb', mdiIcon: 'mdi-leaf', humanReadable: 'MongoDB', url: 'https://www.mongodb.com/' },
  { brandName: 'mysql', mdiIcon: 'mdi-database', humanReadable: 'MySQL', url: 'https://www.mysql.com/' },
  { brandName: 'postgresql', mdiIcon: 'mdi-database', humanReadable: 'PostgreSQL', url: 'https://www.postgresql.org/' },
  { brandName: 'sqlite', mdiIcon: 'mdi-database', humanReadable: 'SQLite', url: 'https://www.sqlite.org/' },
  { brandName: 'firebase', mdiIcon: 'mdi-google', humanReadable: 'Firebase', url: 'https://firebase.google.com/' },
  { brandName: 'aws', mdiIcon: 'mdi-aws', humanReadable: 'AWS', url: 'https://aws.amazon.com/' },
  { brandName: 'azure', mdiIcon: 'mdi-microsoft-azure', humanReadable: 'Azure', url: 'https://azure.microsoft.com/' },
  { brandName: 'googlecloud', mdiIcon: 'mdi-google-cloud', humanReadable: 'Google Cloud', url: 'https://cloud.google.com/' },
  { brandName: 'docker', mdiIcon: 'mdi-docker', humanReadable: 'Docker', url: 'https://www.docker.com/' },
  { brandName: 'kubernetes', mdiIcon: 'mdi-kubernetes', humanReadable: 'Kubernetes', url: 'https://kubernetes.io/' },
  { brandName: 'graphql', mdiIcon: 'mdi-graphql', humanReadable: 'GraphQL', url: 'https://graphql.org/' },
  { brandName: 'prisma', mdiIcon: 'mdi-database', humanReadable: 'Prisma', url: 'https://www.prisma.io/' },
  { brandName: 'redis', mdiIcon: 'mdi-database', humanReadable: 'Redis', url: 'https://redis.io/' },
  { brandName: 'elasticsearch', mdiIcon: 'mdi-magnify', humanReadable: 'Elasticsearch', url: 'https://www.elastic.co/' },
  { brandName: 'kibana', mdiIcon: 'mdi-magnify', humanReadable: 'Kibana', url: 'https://www.elastic.co/kibana/' },
  { brandName: 'jenkins', mdiIcon: 'mdi-hammer', humanReadable: 'Jenkins', url: 'https://www.jenkins.io/' },
  { brandName: 'travisci', mdiIcon: 'mdi-cloud', humanReadable: 'Travis CI', url: 'https://travis-ci.org/' },
  { brandName: 'circleci', mdiIcon: 'mdi-cloud', humanReadable: 'CircleCI', url: 'https://circleci.com/' },
  { brandName: 'terraform', mdiIcon: 'mdi-terraform', humanReadable: 'Terraform', url: 'https://www.terraform.io/' },
  { brandName: 'ansible', mdiIcon: 'mdi-cloud', humanReadable: 'Ansible', url: 'https://www.ansible.com/' },
  { brandName: 'prometheus', mdiIcon: 'mdi-chart-bar', humanReadable: 'Prometheus', url: 'https://prometheus.io/' },
  { brandName: 'grafana', mdiIcon: 'mdi-chart-areaspline', humanReadable: 'Grafana', url: 'https://grafana.com/' },
  { brandName: 'postman', mdiIcon: 'mdi-postman', humanReadable: 'Postman', url: 'https://www.postman.com/' },
  { brandName: 'heroku', mdiIcon: 'mdi-heroku', humanReadable: 'Heroku', url: 'https://www.heroku.com/' },
  { brandName: 'vercel', mdiIcon: 'mdi-cloud', humanReadable: 'Vercel', url: 'https://vercel.com/' },
  { brandName: 'netlify', mdiIcon: '', humanReadable: 'Netlify', url: 'https://www.netlify.com/' },
  { brandName: 'render', mdiIcon: 'mdi-cloud', humanReadable: 'Render', url: 'https://render.com/' },
  { brandName: 'digitalocean', mdiIcon: 'mdi-digital-ocean', humanReadable: 'DigitalOcean', url: 'https://www.digitalocean.com/' },
  { brandName: 'kotlin', mdiIcon: 'mdi-language-kotlin', humanReadable: 'Kotlin', url: 'https://kotlinlang.org/' },
  { brandName: 'java', mdiIcon: 'mdi-language-java', humanReadable: 'Java', url: 'https://www.oracle.com/java/' },
  { brandName: 'swift', mdiIcon: 'mdi-apple', humanReadable: 'Swift', url: 'https://swift.org/' },
  { brandName: 'rust', mdiIcon: 'mdi-language-rust', humanReadable: 'Rust', url: 'https://www.rust-lang.org/' },
  { brandName: 'go', mdiIcon: 'mdi-language-go', humanReadable: 'Go', url: 'https://go.dev/' },
  { brandName: 'flutter', mdiIcon: 'mdi-flutter', humanReadable: 'Flutter', url: 'https://flutter.dev/' },
  { brandName: 'dart', mdiIcon: '', humanReadable: 'Dart', url: 'https://dart.dev/' },
  { brandName: 'graphql', mdiIcon: 'mdi-graphql', humanReadable: 'GraphQL', url: 'https://graphql.org/' },
  { brandName: 'solidity', mdiIcon: 'mdi-ethereum', humanReadable: 'Solidity', url: 'https://soliditylang.org/' },
  { brandName: 'ethereum', mdiIcon: 'mdi-ethereum', humanReadable: 'Ethereum', url: 'https://ethereum.org/' },
  { brandName: 'bitcoin', mdiIcon: 'mdi-bitcoin', humanReadable: 'Bitcoin', url: 'https://bitcoin.org/' },
  { brandName: 'haskell', mdiIcon: 'mdi-language-haskell', humanReadable: 'Haskell', url: 'https://www.haskell.org/' },
  { brandName: 'csharp', mdiIcon: 'mdi-language-csharp', humanReadable: 'C Sharp', url: 'https://learn.microsoft.com/en-us/dotnet/csharp/' },
  { brandName: 'cpp', mdiIcon: 'mdi-language-cpp', humanReadable: 'C Plus Plus', url: 'https://isocpp.org/' },
  { brandName: 'clojure', mdiIcon: 'mdi-language-clojure', humanReadable: 'Clojure', url: 'https://clojure.org/' },
  { brandName: 'elixir', mdiIcon: 'mdi-flask', humanReadable: 'Elixir', url: 'https://elixir-lang.org/' },
  { brandName: 'phoenix', mdiIcon: 'mdi-flask', humanReadable: 'Phoenix', url: 'https://www.phoenixframework.org/' },
  { brandName: 'nestjs', mdiIcon: 'mdi-language-javascript', humanReadable: 'NestJS', url: 'https://nestjs.com/' },
  { brandName: 'strapi', mdiIcon: 'mdi-api', humanReadable: 'Strapi', url: 'https://strapi.io/' },
  { brandName: 'sentry', mdiIcon: 'mdi-alert-circle', humanReadable: 'Sentry', url: 'https://sentry.io/' },
  { brandName: 'snowflake', mdiIcon: 'mdi-snowflake', humanReadable: 'Snowflake', url: 'https://www.snowflake.com/' },
  { brandName: 'bigquery', mdiIcon: 'mdi-database-search', humanReadable: 'BigQuery', url: 'https://cloud.google.com/bigquery' },
  { brandName: 'airflow', mdiIcon: 'mdi-airplane', humanReadable: 'Apache Airflow', url: 'https://airflow.apache.org/' },
  { brandName: 'hadoop', mdiIcon: 'mdi-elephant', humanReadable: 'Hadoop', url: 'https://hadoop.apache.org/' },
  { brandName: 'spark', mdiIcon: 'mdi-flash', humanReadable: 'Apache Spark', url: 'https://spark.apache.org/' },
  { brandName: 'tableau', mdiIcon: 'mdi-table', humanReadable: 'Tableau', url: 'https://www.tableau.com/' },
  { brandName: 'metabase', mdiIcon: 'mdi-database', humanReadable: 'Metabase', url: 'https://www.metabase.com/' },
  { brandName: 'superset', mdiIcon: 'mdi-chart-areaspline', humanReadable: 'Apache Superset', url: 'https://superset.apache.org/' },
  { brandName: 'supabase', mdiIcon: 'mdi-database', humanReadable: 'Supabase', url: 'https://supabase.com/' },
  { brandName: 'plaid', mdiIcon: 'mdi-credit-card', humanReadable: 'Plaid', url: 'https://plaid.com/' },
  { brandName: 'twilio', mdiIcon: 'mdi-phone', humanReadable: 'Twilio', url: 'https://www.twilio.com/' },
  { brandName: 'stripe', mdiIcon: 'mdi-credit-card', humanReadable: 'Stripe', url: 'https://stripe.com/' },
  { brandName: 'paypal', mdiIcon: 'mdi-cash', humanReadable: 'PayPal', url: 'https://www.paypal.com/' },
  { brandName: 'woocommerce', mdiIcon: 'mdi-shopping', humanReadable: 'WooCommerce', url: 'https://woocommerce.com/' },
  { brandName: 'shopify', mdiIcon: 'mdi-cart', humanReadable: 'Shopify', url: 'https://www.shopify.com/' },
  { brandName: 'wordpress', mdiIcon: 'mdi-wordpress', humanReadable: 'WordPress', url: 'https://wordpress.org/' },
  { brandName: 'drupal', mdiIcon: 'mdi-drupal', humanReadable: 'Drupal', url: 'https://www.drupal.org/' },
  { brandName: 'laravel', mdiIcon: 'mdi-laravel', humanReadable: 'Laravel', url: 'https://laravel.com/' },
  { brandName: 'pytorch', mdiIcon: 'mdi-brain', humanReadable: 'PyTorch', url: 'https://pytorch.org/' },
  { brandName: 'tensorflow', mdiIcon: 'mdi-brain', humanReadable: 'TensorFlow', url: 'https://www.tensorflow.org/' },
  { brandName: 'openai', mdiIcon: 'mdi-robot', humanReadable: 'OpenAI', url: 'https://openai.com/' },
  { brandName: 'huggingface', mdiIcon: 'mdi-emoticon', humanReadable: 'Hugging Face', url: 'https://huggingface.co/' },
  { brandName: 'lightgbm', mdiIcon: 'mdi-tree', humanReadable: 'LightGBM', url: 'https://lightgbm.readthedocs.io/' },
  { brandName: 'xgboost', mdiIcon: 'mdi-tree', humanReadable: 'XGBoost', url: 'https://xgboost.readthedocs.io/' }
];