export const brands = [
  { brandName: 'html5', mdiIcon: 'mdi-language-html5', isDark: false, humanReadable: 'HTML5' },
  { brandName: 'css3',  mdiIcon: 'mdi-language-css3', isDark: true, humanReadable: 'CSS3' },
  { brandName: 'javascript',  mdiIcon: 'mdi-language-javascript', isDark: false, humanReadable: 'JavaScript' },
  { brandName: 'typescript',  mdiIcon: 'mdi-language-typescript', isDark: true, humanReadable: 'TypeScript' },
  { brandName: 'react', mdiIcon: 'mdi-react', isDark: false, humanReadable: 'React' },
  { brandName: 'vuejs', mdiIcon: 'mdi-vuejs', isDark: false, humanReadable: 'Vue.js' },
  { brandName: 'angular', mdiIcon: 'mdi-angular', isDark: true, humanReadable: 'Angular' },
  { brandName: 'svelte', mdiIcon: 'mdi-svelte', isDark: false, humanReadable: 'Svelte' },
  { brandName: 'nodejs', mdiIcon: 'mdi-nodejs', isDark: true, humanReadable: 'Node.js' },
  { brandName: 'expressjs', mdiIcon: 'mdi-web', isDark: true, humanReadable: 'Express.js' },
  { brandName: 'php', mdiIcon: 'mdi-language-php', isDark: true, humanReadable: 'PHP' },
  { brandName: 'python', mdiIcon: 'mdi-language-python', isDark: true, humanReadable: 'Python' },
  { brandName: 'django', mdiIcon: 'mdi-web', isDark: true, humanReadable: 'Django' },
  { brandName: 'rubyonrails', mdiIcon: 'mdi-language-ruby-on-rails', isDark: true, humanReadable: 'Ruby on Rails' },
  { brandName: 'aspnet', mdiIcon: 'mdi-microsoft-azure', isDark: true, humanReadable: 'ASP.NET' },
  { brandName: 'bootstrap', mdiIcon: 'mdi-bootstrap', isDark: true, humanReadable: 'Bootstrap' },
  { brandName: 'tailwindcss', mdiIcon: 'mdi-tailwind', isDark: false, humanReadable: 'Tailwind CSS' },
  { brandName: 'jquery', mdiIcon: 'mdi-jquery', isDark: true, humanReadable: 'jQuery' },
  { brandName: 'webpack', mdiIcon: 'mdi-webpack', isDark: false, humanReadable: 'Webpack' },
  { brandName: 'vite', mdiIcon: 'mdi-lightning-bolt', isDark: true, humanReadable: 'Vite' },
  { brandName: 'gatsby', mdiIcon: 'mdi-react', isDark: true, humanReadable: 'Gatsby' },
  { brandName: 'nextjs', mdiIcon: 'mdi-nextjs', isDark: true, humanReadable: 'Next.js' },
  { brandName: 'nuxtjs', mdiIcon: 'mdi-vuejs', isDark: false, humanReadable: 'Nuxt.js' },
  { brandName: 'mongodb', mdiIcon: 'mdi-leaf', isDark: false, humanReadable: 'MongoDB' },
  { brandName: 'mysql', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'MySQL' },
  { brandName: 'postgresql', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'PostgreSQL' },
  { brandName: 'sqlite', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'SQLite' },
  { brandName: 'firebase', mdiIcon: 'mdi-google', isDark: false, humanReadable: 'Firebase' },
  { brandName: 'aws', mdiIcon: 'mdi-aws', isDark: false, humanReadable: 'AWS' },
  { brandName: 'azure', mdiIcon: 'mdi-microsoft-azure', isDark: true, humanReadable: 'Azure' },
  { brandName: 'googlecloud', mdiIcon: 'mdi-google-cloud', isDark: true, humanReadable: 'Google Cloud' },
  { brandName: 'docker', mdiIcon: 'mdi-docker', isDark: true, humanReadable: 'Docker' },
  { brandName: 'kubernetes', mdiIcon: 'mdi-kubernetes', isDark: true, humanReadable: 'Kubernetes' },
  { brandName: 'graphql', mdiIcon: 'mdi-graphql', isDark: true, humanReadable: 'GraphQL' },
  { brandName: 'prisma', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'Prisma' },
  { brandName: 'redis', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'Redis' },
  { brandName: 'elasticsearch', mdiIcon: 'mdi-magnify', isDark: true, humanReadable: 'Elasticsearch' },
  { brandName: 'kibana', mdiIcon: 'mdi-magnify', isDark: true, humanReadable: 'Kibana' },
  { brandName: 'jenkins', mdiIcon: 'mdi-hammer', isDark: true, humanReadable: 'Jenkins' },
  { brandName: 'travisci', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Travis CI' },
  { brandName: 'circleci', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'CircleCI' },
  { brandName: 'terraform', mdiIcon: 'mdi-terraform', isDark: true, humanReadable: 'Terraform' },
  { brandName: 'ansible', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Ansible' },
  { brandName: 'prometheus', mdiIcon: 'mdi-chart-bar', isDark: true, humanReadable: 'Prometheus' },
  { brandName: 'grafana', mdiIcon: 'mdi-chart-areaspline', isDark: false, humanReadable: 'Grafana' },
  { brandName: 'postman', mdiIcon: 'mdi-postman', isDark: false, humanReadable: 'Postman' },
  { brandName: 'heroku', mdiIcon: 'mdi-heroku', isDark: true, humanReadable: 'Heroku' },
  { brandName: 'vercel', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Vercel' },
  { brandName: 'netlify', mdiIcon: '', isDark: false, humanReadable: 'Netlify' },
  { brandName: 'render', mdiIcon: 'mdi-cloud', isDark: false, humanReadable: 'Render' },
  { brandName: 'digitalocean', mdiIcon: 'mdi-digital-ocean', isDark: true, humanReadable: 'DigitalOcean' }
];