export const brands = [
  { brandName: 'html5', mdiIcon: 'mdi-language-html5', isDark: false, humanReadable: 'HTML5' },
  { brandName: 'css3',  mdiIcon: 'mdi-language-css3', isDark: true, humanReadable: 'CSS3' },
  { brandName: 'javascript',  mdiIcon: 'mdi-language-javascript', isDark: false, humanReadable: 'JavaScript' },
  { brandName: 'typescript',  mdiIcon: 'mdi-language-typescript', isDark: true, humanReadable: 'TypeScript' },
  { brandName: 'react', mdiIcon: 'mdi-react', isDark: false, humanReadable: 'React' },
  { brandName: 'vuejs', mdiIcon: 'mdi-vuejs', isDark: false, humanReadable: 'Vue.js' },
  { brandName: 'angular', mdiIcon: 'mdi-angular', isDark: true, humanReadable: 'Angular' },
  { brandName: 'svelte', mdiIcon: 'mdi-svelte', isDark: false, humanReadable: 'Svelte' },
  { brandName: 'nodejs', mdiIcon: 'mdi-nodejs', isDark: true, humanReadable: 'Node.js' },
  { brandName: 'expressjs', mdiIcon: 'mdi-web', isDark: true, humanReadable: 'Express.js' },
  { brandName: 'php', mdiIcon: 'mdi-language-php', isDark: true, humanReadable: 'PHP' },
  { brandName: 'python', mdiIcon: 'mdi-language-python', isDark: true, humanReadable: 'Python' },
  { brandName: 'django', mdiIcon: 'mdi-web', isDark: true, humanReadable: 'Django' },
  { brandName: 'rubyonrails', mdiIcon: 'mdi-language-ruby-on-rails', isDark: true, humanReadable: 'Ruby on Rails' },
  { brandName: 'aspnet', mdiIcon: 'mdi-microsoft-azure', isDark: true, humanReadable: 'ASP.NET' },
  { brandName: 'bootstrap', mdiIcon: 'mdi-bootstrap', isDark: true, humanReadable: 'Bootstrap' },
  { brandName: 'tailwindcss', mdiIcon: 'mdi-tailwind', isDark: false, humanReadable: 'Tailwind CSS' },
  { brandName: 'jquery', mdiIcon: 'mdi-jquery', isDark: true, humanReadable: 'jQuery' },
  { brandName: 'webpack', mdiIcon: 'mdi-webpack', isDark: false, humanReadable: 'Webpack' },
  { brandName: 'vite', mdiIcon: 'mdi-lightning-bolt', isDark: true, humanReadable: 'Vite' },
  { brandName: 'gatsby', mdiIcon: 'mdi-react', isDark: true, humanReadable: 'Gatsby' },
  { brandName: 'nextjs', mdiIcon: 'mdi-react', isDark: true, humanReadable: 'Next.js' },
  { brandName: 'nuxtjs', mdiIcon: 'mdi-vuejs', isDark: false, humanReadable: 'Nuxt.js' },
  { brandName: 'mongodb', mdiIcon: 'mdi-leaf', isDark: false, humanReadable: 'MongoDB' },
  { brandName: 'mysql', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'MySQL' },
  { brandName: 'postgresql', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'PostgreSQL' },
  { brandName: 'sqlite', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'SQLite' },
  { brandName: 'firebase', mdiIcon: 'mdi-google', isDark: false, humanReadable: 'Firebase' },
  { brandName: 'aws', mdiIcon: 'mdi-aws', isDark: false, humanReadable: 'AWS' },
  { brandName: 'azure', mdiIcon: 'mdi-microsoft-azure', isDark: true, humanReadable: 'Azure' },
  { brandName: 'googlecloud', mdiIcon: 'mdi-google-cloud', isDark: true, humanReadable: 'Google Cloud' },
  { brandName: 'docker', mdiIcon: 'mdi-docker', isDark: true, humanReadable: 'Docker' },
  { brandName: 'kubernetes', mdiIcon: 'mdi-kubernetes', isDark: true, humanReadable: 'Kubernetes' },
  { brandName: 'graphql', mdiIcon: 'mdi-graphql', isDark: true, humanReadable: 'GraphQL' },
  { brandName: 'prisma', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'Prisma' },
  { brandName: 'redis', mdiIcon: 'mdi-database', isDark: true, humanReadable: 'Redis' },
  { brandName: 'elasticsearch', mdiIcon: 'mdi-magnify', isDark: true, humanReadable: 'Elasticsearch' },
  { brandName: 'kibana', mdiIcon: 'mdi-magnify', isDark: true, humanReadable: 'Kibana' },
  { brandName: 'jenkins', mdiIcon: 'mdi-hammer', isDark: true, humanReadable: 'Jenkins' },
  { brandName: 'travisci', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Travis CI' },
  { brandName: 'circleci', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'CircleCI' },
  { brandName: 'terraform', mdiIcon: 'mdi-terraform', isDark: true, humanReadable: 'Terraform' },
  { brandName: 'ansible', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Ansible' },
  { brandName: 'prometheus', mdiIcon: 'mdi-chart-bar', isDark: true, humanReadable: 'Prometheus' },
  { brandName: 'grafana', mdiIcon: 'mdi-chart-areaspline', isDark: false, humanReadable: 'Grafana' },
  { brandName: 'postman', mdiIcon: 'mdi-postman', isDark: false, humanReadable: 'Postman' },
  { brandName: 'heroku', mdiIcon: 'mdi-heroku', isDark: true, humanReadable: 'Heroku' },
  { brandName: 'vercel', mdiIcon: 'mdi-cloud', isDark: true, humanReadable: 'Vercel' },
  { brandName: 'netlify', mdiIcon: '', isDark: false, humanReadable: 'Netlify' },
  { brandName: 'render', mdiIcon: 'mdi-cloud', isDark: false, humanReadable: 'Render' },
  { brandName: 'digitalocean', mdiIcon: 'mdi-digital-ocean', isDark: true, humanReadable: 'DigitalOcean' },
  { brandName: 'kotlin', mdiIcon: 'mdi-language-kotlin', isDark: false, humanReadable: 'Kotlin' },
  { brandName: 'java', mdiIcon: 'mdi-language-java', isDark: true, humanReadable: 'Java' },
  { brandName: 'swift', mdiIcon: 'mdi-apple', isDark: false, humanReadable: 'Swift' },
  { brandName: 'rust', mdiIcon: 'mdi-language-rust', isDark: false, humanReadable: 'Rust' },
  { brandName: 'go', mdiIcon: 'mdi-language-go', isDark: false, humanReadable: 'Go' },
  { brandName: 'flutter', mdiIcon: 'mdi-flutter', isDark: false, humanReadable: 'Flutter' },
  { brandName: 'dart', mdiIcon: '', isDark: false, humanReadable: 'Dart' },
  { brandName: 'graphql', mdiIcon: 'mdi-graphql', isDark: true, humanReadable: 'GraphQL' },
  { brandName: 'solidity', mdiIcon: 'mdi-ethereum', isDark: true, humanReadable: 'Solidity' },
  { brandName: 'ethereum', mdiIcon: 'mdi-ethereum', isDark: true, humanReadable: 'Ethereum' },
  { brandName: 'bitcoin', mdiIcon: 'mdi-bitcoin', isDark: false, humanReadable: 'Bitcoin' },
  { brandName: 'haskell', mdiIcon: 'mdi-language-haskell', isDark: true, humanReadable: 'Haskell' },
  { brandName: 'csharp', mdiIcon: 'mdi-language-csharp', isDark: true, humanReadable: 'C Sharp' },
  { brandName: 'cpp', mdiIcon: 'mdi-language-cpp', isDark: true, humanReadable: 'C Plus Plus' },
  { brandName: 'clojure', mdiIcon: 'mdi-language-clojure', isDark: true, humanReadable: 'Clojure' },
  { brandName: 'elixir', mdiIcon: 'mdi-flask', isDark: false, humanReadable: 'Elixir' },
  { brandName: 'phoenix', mdiIcon: 'mdi-flask', isDark: false, humanReadable: 'Phoenix' },
  { brandName: 'nestjs', mdiIcon: 'mdi-language-javascript', isDark: false, humanReadable: 'NestJS' },
  { brandName: 'strapi', mdiIcon: 'mdi-api', isDark: false, humanReadable: 'Strapi' },
  { brandName: 'sentry', mdiIcon: 'mdi-alert-circle', isDark: true, humanReadable: 'Sentry' },
  { brandName: 'snowflake', mdiIcon: 'mdi-snowflake', isDark: false, humanReadable: 'Snowflake' },
  { brandName: 'bigquery', mdiIcon: 'mdi-database-search', isDark: true, humanReadable: 'BigQuery' },
  { brandName: 'airflow', mdiIcon: 'mdi-airplane', isDark: false, humanReadable: 'Apache Airflow' },
  { brandName: 'hadoop', mdiIcon: 'mdi-elephant', isDark: true, humanReadable: 'Hadoop' },
  { brandName: 'spark', mdiIcon: 'mdi-flash', isDark: true, humanReadable: 'Apache Spark' },
  { brandName: 'tableau', mdiIcon: 'mdi-table', isDark: true, humanReadable: 'Tableau' },
  { brandName: 'metabase', mdiIcon: 'mdi-database', isDark: false, humanReadable: 'Metabase' },
  { brandName: 'superset', mdiIcon: 'mdi-chart-areaspline', isDark: true, humanReadable: 'Apache Superset' },
  { brandName: 'supabase', mdiIcon: 'mdi-database', isDark: false, humanReadable: 'Supabase' },
  { brandName: 'plaid', mdiIcon: 'mdi-credit-card', isDark: false, humanReadable: 'Plaid' },
  { brandName: 'twilio', mdiIcon: 'mdi-phone', isDark: false, humanReadable: 'Twilio' },
  { brandName: 'stripe', mdiIcon: 'mdi-credit-card', isDark: true, humanReadable: 'Stripe' },
  { brandName: 'paypal', mdiIcon: 'mdi-cash', isDark: true, humanReadable: 'PayPal' },
  { brandName: 'woocommerce', mdiIcon: 'mdi-shopping', isDark: false, humanReadable: 'WooCommerce' },
  { brandName: 'shopify', mdiIcon: 'mdi-cart', isDark: false, humanReadable: 'Shopify' },
  { brandName: 'wordpress', mdiIcon: 'mdi-wordpress', isDark: false, humanReadable: 'WordPress' },
  { brandName: 'drupal', mdiIcon: 'mdi-drupal', isDark: true, humanReadable: 'Drupal' },
  { brandName: 'laravel', mdiIcon: 'mdi-laravel', isDark: true, humanReadable: 'Laravel' },
  { brandName: 'pytorch', mdiIcon: 'mdi-brain', isDark: true, humanReadable: 'PyTorch' },
  { brandName: 'tensorflow', mdiIcon: 'mdi-brain', isDark: false, humanReadable: 'TensorFlow' },
  { brandName: 'openai', mdiIcon: 'mdi-robot', isDark: false, humanReadable: 'OpenAI' },
  { brandName: 'huggingface', mdiIcon: 'mdi-emoticon', isDark: false, humanReadable: 'Hugging Face' },
  { brandName: 'lightgbm', mdiIcon: 'mdi-tree', isDark: false, humanReadable: 'LightGBM' },
  { brandName: 'xgboost', mdiIcon: 'mdi-tree', isDark: true, humanReadable: 'XGBoost' }
];